[workspace]
resolver = "3"

members = [
# evm-sys
    "src/target/evm-sys-macros",
    "src/target/evm-sys",
# target-evm
    "src/target/std-evm",
    "src/target/std-evm-macros",
# SHARED
    "src/target/std-evm-abi",
    "src/shared/evm-isa",
# BACKEND
    "src/backend/evm-codegen",
    "src/backend/rustc_codegen_evm",
# TOOLING
    "src/tooling/evm-testkit",
# EXAMPLES
    "examples/my-first-contract",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Lee Harman <lee.harman@outlook.com>"]