[workspace]
resolver = "3"
members = [
# evm-sys
    "src/std/evm-sys-macros",
    "src/std/evm-sys",
# std-evm
    "src/std/std-evm",
    "src/std/std-evm-macros",
# shared
    "src/std/std-evm-abi",
# BACKEND
    "src/backend/evm-isa",
    "src/backend/evm-codegen",
    "src/backend/rustc_codegen_evm",
# EXAMPLES
    "examples/my-first-contract",
]
