use crate::category::OpCategory::{self, *};
use crate::fork::Fork::{self, *};
use crate::gas::GasClass::{self, *};
use crate::spec::OpSpec;

// One argument per `OpSpec` field, in field order — a positional literal
// would be exactly as long.
#[allow(clippy::too_many_arguments)]
const fn op(
    mnemonic: &'static str,
    byte: u8,
    stack_in: u8,
    stack_out: u8,
    terminating: bool,
    gas: GasClass,
    category: OpCategory,
    min_fork: Fork,
) -> OpSpec {
    OpSpec {
        mnemonic,
        byte,
        stack_in,
        stack_out,
        terminating,
        gas,
        category,
        min_fork,
    }
}

/// `PUSH1..PUSH32`: no stack inputs, push a 1..32-byte immediate. Every
/// width costs the same verylow-tier 3 gas.
const fn push_spec(mnemonic: &'static str, n: u8) -> OpSpec {
    op(
        mnemonic,
        0x5f + n,
        0,
        1,
        false,
        Fixed(3),
        StackManip,
        Frontier,
    )
}

/// `DUP1..DUP16`: duplicate the `n`-th stack item onto the top.
const fn dup_spec(mnemonic: &'static str, n: u8) -> OpSpec {
    op(
        mnemonic,
        0x7f + n,
        n,
        n + 1,
        false,
        Fixed(3),
        StackManip,
        Frontier,
    )
}

/// `SWAP1..SWAP16`: swap the top with the `(n+1)`-th stack item.
const fn swap_spec(mnemonic: &'static str, n: u8) -> OpSpec {
    op(
        mnemonic,
        0x8f + n,
        n + 1,
        n + 1,
        false,
        Fixed(3),
        StackManip,
        Frontier,
    )
}

/// The canonical EVM opcode table — one row per byte value, ~149 entries.
///
/// Grouped below by Yellow Paper section, which is also how [`OpCategory`]
/// is assigned: 0x00s Stop & Arithmetic, 0x10s Comparison & Bitwise, 0x20s
/// `KECCAK256`, 0x30s Environmental Information, 0x40s Block Information,
/// 0x50s Stack/Memory/Storage/Flow, 0x60s-0x9fs Push/Dup/Swap, 0xa0s Log,
/// 0xf0s System operations.
pub const OPCODES: &[OpSpec] = &[
    // ── 0x00s: stop & arithmetic ────────────────────────────────────────
    op("STOP", 0x00, 0, 0, true, Zero, Terminating, Frontier),
    op("ADD", 0x01, 2, 1, false, Fixed(3), Arithmetic, Frontier),
    op("MUL", 0x02, 2, 1, false, Fixed(5), Arithmetic, Frontier),
    op("SUB", 0x03, 2, 1, false, Fixed(3), Arithmetic, Frontier),
    op("DIV", 0x04, 2, 1, false, Fixed(5), Arithmetic, Frontier),
    op("SDIV", 0x05, 2, 1, false, Fixed(5), Arithmetic, Frontier),
    op("MOD", 0x06, 2, 1, false, Fixed(5), Arithmetic, Frontier),
    op("SMOD", 0x07, 2, 1, false, Fixed(5), Arithmetic, Frontier),
    op("ADDMOD", 0x08, 3, 1, false, Fixed(8), Arithmetic, Frontier),
    op("MULMOD", 0x09, 3, 1, false, Fixed(8), Arithmetic, Frontier),
    op(
        "EXP",
        0x0a,
        2,
        1,
        false,
        PerByteOfExponent(50),
        Arithmetic,
        Frontier,
    ),
    op(
        "SIGNEXTEND",
        0x0b,
        2,
        1,
        false,
        Fixed(5),
        Arithmetic,
        Frontier,
    ),
    // ── 0x10s: comparison & bitwise ──────────────────────────────────────
    op("LT", 0x10, 2, 1, false, Fixed(3), Comparison, Frontier),
    op("GT", 0x11, 2, 1, false, Fixed(3), Comparison, Frontier),
    op("SLT", 0x12, 2, 1, false, Fixed(3), Comparison, Frontier),
    op("SGT", 0x13, 2, 1, false, Fixed(3), Comparison, Frontier),
    op("EQ", 0x14, 2, 1, false, Fixed(3), Comparison, Frontier),
    op("ISZERO", 0x15, 1, 1, false, Fixed(3), Comparison, Frontier),
    op("AND", 0x16, 2, 1, false, Fixed(3), Bitwise, Frontier),
    op("OR", 0x17, 2, 1, false, Fixed(3), Bitwise, Frontier),
    op("XOR", 0x18, 2, 1, false, Fixed(3), Bitwise, Frontier),
    op("NOT", 0x19, 1, 1, false, Fixed(3), Bitwise, Frontier),
    op("BYTE", 0x1a, 2, 1, false, Fixed(3), Bitwise, Frontier),
    op("SHL", 0x1b, 2, 1, false, Fixed(3), Bitwise, Constantinople),
    op("SHR", 0x1c, 2, 1, false, Fixed(3), Bitwise, Constantinople),
    op("SAR", 0x1d, 2, 1, false, Fixed(3), Bitwise, Constantinople),
    // ── 0x20s: keccak256 ─────────────────────────────────────────────────
    op("KECCAK256", 0x20, 2, 1, false, PerWord(6), Memory, Frontier),
    // ── 0x30s: environmental information ────────────────────────────────
    op("ADDRESS", 0x30, 0, 1, false, Fixed(2), Context, Frontier),
    op(
        "BALANCE",
        0x31,
        1,
        1,
        false,
        ColdWarm {
            cold: 2600,
            warm: 100,
        },
        Context,
        Frontier,
    ),
    op("ORIGIN", 0x32, 0, 1, false, Fixed(2), Context, Frontier),
    op("CALLER", 0x33, 0, 1, false, Fixed(2), Context, Frontier),
    op("CALLVALUE", 0x34, 0, 1, false, Fixed(2), Context, Frontier),
    op(
        "CALLDATALOAD",
        0x35,
        1,
        1,
        false,
        Fixed(3),
        Context,
        Frontier,
    ),
    op(
        "CALLDATASIZE",
        0x36,
        0,
        1,
        false,
        Fixed(2),
        Context,
        Frontier,
    ),
    op(
        "CALLDATACOPY",
        0x37,
        3,
        0,
        false,
        PerWord(3),
        Context,
        Frontier,
    ),
    op("CODESIZE", 0x38, 0, 1, false, Fixed(2), Context, Frontier),
    op("CODECOPY", 0x39, 3, 0, false, PerWord(3), Context, Frontier),
    op("GASPRICE", 0x3a, 0, 1, false, Fixed(2), Context, Frontier),
    op(
        "EXTCODESIZE",
        0x3b,
        1,
        1,
        false,
        ColdWarm {
            cold: 2600,
            warm: 100,
        },
        Context,
        Frontier,
    ),
    op(
        "EXTCODECOPY",
        0x3c,
        4,
        0,
        false,
        ColdWarm {
            cold: 2600,
            warm: 100,
        },
        Context,
        Frontier,
    ),
    op(
        "RETURNDATASIZE",
        0x3d,
        0,
        1,
        false,
        Fixed(2),
        Context,
        Byzantium,
    ),
    op(
        "RETURNDATACOPY",
        0x3e,
        3,
        0,
        false,
        PerWord(3),
        Context,
        Byzantium,
    ),
    op(
        "EXTCODEHASH",
        0x3f,
        1,
        1,
        false,
        ColdWarm {
            cold: 2600,
            warm: 100,
        },
        Context,
        Constantinople,
    ),
    // ── 0x40s: block information ─────────────────────────────────────────
    op("BLOCKHASH", 0x40, 1, 1, false, Fixed(20), Block, Frontier),
    op("COINBASE", 0x41, 0, 1, false, Fixed(2), Block, Frontier),
    op("TIMESTAMP", 0x42, 0, 1, false, Fixed(2), Block, Frontier),
    op("NUMBER", 0x43, 0, 1, false, Fixed(2), Block, Frontier),
    op("PREVRANDAO", 0x44, 0, 1, false, Fixed(2), Block, Frontier),
    op("GASLIMIT", 0x45, 0, 1, false, Fixed(2), Block, Frontier),
    op("CHAINID", 0x46, 0, 1, false, Fixed(2), Block, Istanbul),
    op(
        "SELFBALANCE",
        0x47,
        0,
        1,
        false,
        Fixed(5),
        Context,
        Istanbul,
    ),
    op("BASEFEE", 0x48, 0, 1, false, Fixed(2), Block, London),
    op("BLOBHASH", 0x49, 1, 1, false, Fixed(3), Block, Cancun),
    op("BLOBBASEFEE", 0x4a, 0, 1, false, Fixed(2), Block, Cancun),
    // ── 0x50s: stack, memory, storage, flow ─────────────────────────────
    op("POP", 0x50, 1, 0, false, Fixed(2), StackManip, Frontier),
    op(
        "MLOAD",
        0x51,
        1,
        1,
        false,
        MemoryExpansion,
        Memory,
        Frontier,
    ),
    op(
        "MSTORE",
        0x52,
        2,
        0,
        false,
        MemoryExpansion,
        Memory,
        Frontier,
    ),
    op(
        "MSTORE8",
        0x53,
        2,
        0,
        false,
        MemoryExpansion,
        Memory,
        Frontier,
    ),
    op(
        "SLOAD",
        0x54,
        1,
        1,
        false,
        ColdWarm {
            cold: 2100,
            warm: 100,
        },
        Storage,
        Frontier,
    ),
    op("SSTORE", 0x55, 2, 0, false, StorageWrite, Storage, Frontier),
    op("JUMP", 0x56, 1, 0, false, Fixed(8), Control, Frontier),
    op("JUMPI", 0x57, 2, 0, false, Fixed(10), Control, Frontier),
    op("PC", 0x58, 0, 1, false, Fixed(2), Control, Frontier),
    op("MSIZE", 0x59, 0, 1, false, Fixed(2), Memory, Frontier),
    op("GAS", 0x5a, 0, 1, false, Fixed(2), Context, Frontier),
    op("JUMPDEST", 0x5b, 0, 0, false, Fixed(1), Control, Frontier),
    op("TLOAD", 0x5c, 1, 1, false, Fixed(100), Storage, Cancun),
    op("TSTORE", 0x5d, 2, 0, false, Fixed(100), Storage, Cancun),
    op("MCOPY", 0x5e, 3, 0, false, PerWord(3), Memory, Cancun),
    op("PUSH0", 0x5f, 0, 1, false, Fixed(2), StackManip, Shanghai),
    // ── 0x60s-0x7fs: PUSH1-PUSH32 ────────────────────────────────────────
    push_spec("PUSH1", 1),
    push_spec("PUSH2", 2),
    push_spec("PUSH3", 3),
    push_spec("PUSH4", 4),
    push_spec("PUSH5", 5),
    push_spec("PUSH6", 6),
    push_spec("PUSH7", 7),
    push_spec("PUSH8", 8),
    push_spec("PUSH9", 9),
    push_spec("PUSH10", 10),
    push_spec("PUSH11", 11),
    push_spec("PUSH12", 12),
    push_spec("PUSH13", 13),
    push_spec("PUSH14", 14),
    push_spec("PUSH15", 15),
    push_spec("PUSH16", 16),
    push_spec("PUSH17", 17),
    push_spec("PUSH18", 18),
    push_spec("PUSH19", 19),
    push_spec("PUSH20", 20),
    push_spec("PUSH21", 21),
    push_spec("PUSH22", 22),
    push_spec("PUSH23", 23),
    push_spec("PUSH24", 24),
    push_spec("PUSH25", 25),
    push_spec("PUSH26", 26),
    push_spec("PUSH27", 27),
    push_spec("PUSH28", 28),
    push_spec("PUSH29", 29),
    push_spec("PUSH30", 30),
    push_spec("PUSH31", 31),
    push_spec("PUSH32", 32),
    // ── 0x80s: DUP1-DUP16 ─────────────────────────────────────────────────
    dup_spec("DUP1", 1),
    dup_spec("DUP2", 2),
    dup_spec("DUP3", 3),
    dup_spec("DUP4", 4),
    dup_spec("DUP5", 5),
    dup_spec("DUP6", 6),
    dup_spec("DUP7", 7),
    dup_spec("DUP8", 8),
    dup_spec("DUP9", 9),
    dup_spec("DUP10", 10),
    dup_spec("DUP11", 11),
    dup_spec("DUP12", 12),
    dup_spec("DUP13", 13),
    dup_spec("DUP14", 14),
    dup_spec("DUP15", 15),
    dup_spec("DUP16", 16),
    // ── 0x90s: SWAP1-SWAP16 ───────────────────────────────────────────────
    swap_spec("SWAP1", 1),
    swap_spec("SWAP2", 2),
    swap_spec("SWAP3", 3),
    swap_spec("SWAP4", 4),
    swap_spec("SWAP5", 5),
    swap_spec("SWAP6", 6),
    swap_spec("SWAP7", 7),
    swap_spec("SWAP8", 8),
    swap_spec("SWAP9", 9),
    swap_spec("SWAP10", 10),
    swap_spec("SWAP11", 11),
    swap_spec("SWAP12", 12),
    swap_spec("SWAP13", 13),
    swap_spec("SWAP14", 14),
    swap_spec("SWAP15", 15),
    swap_spec("SWAP16", 16),
    // ── 0xa0s: logging ───────────────────────────────────────────────────
    op("LOG0", 0xa0, 2, 0, false, Complex, Log, Frontier),
    op("LOG1", 0xa1, 3, 0, false, Complex, Log, Frontier),
    op("LOG2", 0xa2, 4, 0, false, Complex, Log, Frontier),
    op("LOG3", 0xa3, 5, 0, false, Complex, Log, Frontier),
    op("LOG4", 0xa4, 6, 0, false, Complex, Log, Frontier),
    // ── 0xf0s: system operations ────────────────────────────────────────
    op("CREATE", 0xf0, 3, 1, false, Complex, Call, Frontier),
    op("CALL", 0xf1, 7, 1, false, Complex, Call, Frontier),
    op("CALLCODE", 0xf2, 7, 1, false, Complex, Call, Frontier),
    op("RETURN", 0xf3, 2, 0, true, Zero, Terminating, Frontier),
    op("DELEGATECALL", 0xf4, 6, 1, false, Complex, Call, Homestead),
    op("CREATE2", 0xf5, 4, 1, false, Complex, Call, Constantinople),
    op("STATICCALL", 0xfa, 6, 1, false, Complex, Call, Byzantium),
    op("REVERT", 0xfd, 2, 0, true, Zero, Terminating, Byzantium),
    op("INVALID", 0xfe, 0, 0, true, All, Terminating, Frontier),
    op(
        "SELFDESTRUCT",
        0xff,
        1,
        0,
        true,
        Complex,
        Terminating,
        Frontier,
    ),
];
